### ISSUE TITLE
100% value and threeshold

### ISSUE THREAD

**Issue by sgtnourry** [cm971991/cmGauge#1]
Hi, 

Tks for your work. 
I find a little issue with this code, when the percentage is 100% the background color turn to black. I've tried to fix it but I not in ease with JS and i miserably failed :) 
Also i would put some thresshold on the grap like : when the percentage is over 80 the back is green, yellow for 80 ==>70 % and red below. 
Can you help me with this ? 

Tks in advance ,

**Comment by cm971991** [comment]
thank you
I have already fixed the bug
